name: Deploy Next.js to GitHub Pages (User Site)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # important for avoiding permission errors

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to main branch root
      run: |
        # Move build output to a temp folder
        mv out ../out-temp

        # Remove everything in the repo
        rm -rf ./* .[^.]*

        # Move built site back to root
        mv ../out-temp/* ./
        rm -rf ../out-temp

        # Commit and push
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Deploy site" || echo "No changes to commit"
        git push origin main
